### ISSUE TITLE
Latest API updates changes image URLs

### ISSUE THREAD

**Issue by Jayphen** [datocms/js-datocms-client#8]
The image URL returned from the API previously ended with `?`. This has changed with the latest API updates, which potentially breaks URLs if query strings were appended to them (this just happened to me).

Was this intentional, or will it be reverting to the previous response?

**Comment by stefanoverna** [comment]
can you give me a failing example please? what version are you using?

2017-10-17 2:33 GMT+02:00 Jayphen <notifications@github.com>:

**Comment by Jayphen** [comment]
Currently using 0.3.32.

I am not sure how to provide an example, but as of 0.3.32, this:
```
image: data.image.toMap()
```

returns 

```
image:
  format: jpg
  size: 175932
  width: 522
  height: 784
  title: null
  alt: null
  url: 'https://www.datocms-assets.com/3434/1507806168-torch.jpg'
```

where it previously returned

```
image:
  format: jpg
  size: 175932
  width: 522
  height: 784
  title: null
  alt: null
  url: 'https://www.datocms-assets.com/3434/1507806168-torch.jpg?'
```

Note the `?` at the end of the URL previously.

I was using this in my view (Hugo) with query params attached like so:

```
<img src="{{ .image.url }}crop=fit&w=200">
```

which would return

```
<img src="https://www.datocms-assets.com/3434/1507806168-torch.jpg?crop=fit&w=200">
```

but now returns

```
<img src="https://www.datocms-assets.com/3434/1507806168-torch.jpgcrop=fit&w=200">
```

which is a broken path.
